name: 'Build and Push Service'
description: 'Builds and pushes a Docker image for a specific service'
inputs:
  service:
    description: 'Name of the service to build'
    required: true
  image_namespace:
    description: 'Docker Hub namespace'
    required: true
  dockerhub_username:
    description: 'Docker Hub username'
    required: true
  dockerhub_token:
    description: 'Docker Hub token'
    required: true
  image_name:
    description: 'Name of the Docker image'
    required: true
  tag:
    description: 'Tag for the Docker image'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ inputs.service }}
        file: ./${{ inputs.service }}/Dockerfile
        push: true
        tags: |
          ${{ inputs.image_namespace }}/${{ inputs.image_name }}:${{ inputs.tag }}
